### ISSUE TITLE
[US24] exportar dados para o formato KML para os pontos/área 

### ISSUE THREAD

**Issue by gdeusdara** [fga-eps-mds/2021.1-Cartografia-social-api-mapas#24]
# Descrição:
 exportar dados para o formato KML para os pontos/área na api de Gateway

# Tarefas:
- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3 ...

# Critério de aceitação:
- [ ] Critério de aceitação 1
- [ ] Critério de aceitação 2
- [ ] Critério de aceitação 3 ...

**Comment by leossb36** [comment]
issue não é necessária para este serviço, portanto estarei fechando.
